src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['product_browse'])]
    private ?int $id = null;

    #[ORM\Column(length: 64)]
    #[Groups(['product_browse'])]
    private ?string $name = null;

    #[ORM\Column(length: 64, nullable: true)]
    private ?string $subtitle = null;

    #[ORM\Column(length: 128, nullable: true)]
    private ?string $picture = null;

    #[ORM\Column]
    #[Groups(['product_browse'])]
    private ?int $home_order = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    /**
     * @var Collection<int, Product>
     */
    #[ORM\ManyToMany(targetEntity: Product::class, mappedBy: 'category')]
    private Collection $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->created_at = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(?string $subtitle): static
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHomeOrder(): ?int
    {
        return $this->home_order;
    }

    public function setHomeOrder(int $home_order): static
    {
        $this->home_order = $home_order;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->addCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            $product->removeCategory($this);
        }

        return $this;
    }
}

src/Controller/Api/V1/CategoryController.php
<?php

namespace App\Controller\Api\V1;

use App\Entity\Category;
use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/api/v1/category', name: 'app_api_v1_category_')]
class CategoryController extends AbstractController
{
    #[Route('/', name: 'browse')]
    public function browse(CategoryRepository $categoryRepository): JsonResponse
    {
        return $this->json($categoryRepository->findAll(), 200, [], ['groups' => 'product_browse']);
    }



    #[Route('/{id}', name: 'products', methods: ["GET"], requirements: ["id" => "\d+"])]
    public function products(Category $category): JsonResponse
    {
        return $this->json($category->getProducts(), 200, [], ['groups' => 'product_browse']);
    }
}

src/Controller/Back/BrandController.php
<?php

namespace App\Controller\Back;

use App\Entity\Brand;
use App\Form\BrandType;
use App\Repository\BrandRepository;
use App\Service\Pagination;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/back/brand')]
class BrandController extends AbstractController
{
    #[Route('/', name: 'app_back_brand_index', methods: ['GET'])]
    public function index(BrandRepository $brandRepository, Pagination $pagination, Request $request): Response
    {
        $page = $request->query->getInt('page', 1);
        $brands = $pagination->paginateItem($page, $brandRepository->findAll());

        return $this->render('back/brand/index.html.twig', [
            'brands' => $brands,
        ]);
    }

    #[Route('/new', name: 'app_back_brand_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $brand = new Brand();
        $form = $this->createForm(BrandType::class, $brand);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($brand);
            $entityManager->flush();

            return $this->redirectToRoute('app_back_brand_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/brand/new.html.twig', [
            'brand' => $brand,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_back_brand_show', methods: ['GET'])]
    public function show(Brand $brand): Response
    {
        return $this->render('back/brand/show.html.twig', [
            'brand' => $brand,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_back_brand_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Brand $brand, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(BrandType::class, $brand);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $brand->setUpdatedAt(new DateTimeImmutable());
            $entityManager->flush();

            return $this->redirectToRoute('app_back_brand_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/brand/edit.html.twig', [
            'brand' => $brand,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_back_brand_delete', methods: ['POST'])]
    public function delete(Request $request, Brand $brand, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$brand->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($brand);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_back_brand_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/CategoryController.php
<?php

namespace App\Controller\Back;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use App\Service\Pagination;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/back/category')]
class CategoryController extends AbstractController
{
    #[Route('/', name: 'app_back_category_browse', methods: ['GET'])]
    public function browse(CategoryRepository $categoryRepository, Pagination $pagination, Request $request): Response
    {
        $page = $request->query->getInt('page', 1);
        $categories = $pagination->paginateItem($page, $categoryRepository->findAll());

        return $this->render('back/category/index.html.twig', [
            'categories' => $categories,
        ]);
    }

    #[Route('/add', name: 'app_back_category_add', methods: ['GET', 'POST'])]
    public function add(Request $request, EntityManagerInterface $entityManager, CategoryRepository $cateRepo): Response
    {
        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            if($category->getHomeOrder() > 0){

                $allHomeCategory = $cateRepo->getHomeOrder();
                $allHomeCategory[$category->getHomeOrder()]->setHomeOrder(0);
            }
            $entityManager->persist($category);



            $entityManager->flush();

            return $this->redirectToRoute('app_back_category_browse', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/category/new.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_back_category_read', methods: ['GET'])]
    public function show(Category $category): Response
    {
        return $this->render('back/category/show.html.twig', [
            'category' => $category,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_back_category_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Category $category, EntityManagerInterface $entityManager, CategoryRepository $cateRepo): Response
    {
        $actualHomeOrder = $category->getHomeOrder();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $category->setUpdatedAt(new DateTimeImmutable());

            if($category->getHomeOrder() > 0)
            {
                $allHomeCategory = $cateRepo->getHomeOrder();
                $allHomeCategory[$category->getHomeOrder()]->setHomeOrder($actualHomeOrder); 
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_back_category_browse', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/category/edit.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_back_category_delete', methods: ['POST'])]
    public function delete(Request $request, Category $category, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($category);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_back_category_browse', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/MainController.php
<?php

namespace App\Controller\Back;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/back', name: 'app_back_')]
class MainController extends AbstractController
{
    #[Route('/', name: 'main')]
    public function index(): Response
    {
        return $this->render('/back/main/index.html.twig', [
            'controller_name' => 'MainController',
        ]);
    }
}

src/Controller/Back/ProductController.php
<?php

namespace App\Controller\Back;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use App\Service\Pagination;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/back/product', name: 'app_back_product_')]
class ProductController extends AbstractController
{
    #[Route('/', name: 'browse', methods: ['GET'])]
    public function index(ProductRepository $productRepository, Pagination $pagination, Request $request): Response
    {
        $page = $request->query->getInt('page', 1);
        $products = $pagination->paginateItem($page, $productRepository->findAll());

        return $this->render('back/product/index.html.twig', [
            'products' => $products,
        ]);
    }

    #[Route('/add', name: 'add', methods: ['GET', 'POST'])]
    public function add(Request $request, EntityManagerInterface $entityManager): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('app_back_product_browse', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/product/new.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'read', methods: ['GET'])]
    public function read(Product $product): Response
    {
        return $this->render('back/product/show.html.twig', [
            'product' => $product,
        ]);
    }

    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Product $product, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $product->setUpdatedAt(new DateTimeImmutable());
            $entityManager->flush();

            return $this->redirectToRoute('app_back_product_browse', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/product/edit.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'delete', methods: ['POST'])]
    public function delete(Request $request, Product $product, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_back_product_browse', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/TypeController.php
<?php

namespace App\Controller\Back;

use App\Entity\Type;
use App\Form\TypeType;
use App\Repository\TypeRepository;
use App\Service\Pagination;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/back/type', name: 'app_back_type_')]
class TypeController extends AbstractController
{
    #[Route('/', name: 'index', methods: ['GET'])]
    public function index(TypeRepository $typeRepository, Pagination $pagination, Request $request): Response
    {
        $page = $request->query->getInt('page', 1);
        $types = $pagination->paginateItem($page, $typeRepository->findAll());

        return $this->render('back/type/index.html.twig', [
            'types' => $types,
        ]);
    }

    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $type = new Type();
        $form = $this->createForm(TypeType::class, $type);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($type);
            $entityManager->flush();

            return $this->redirectToRoute('app_back_type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/type/new.html.twig', [
            'type' => $type,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'show', methods: ['GET'])]
    public function show(Type $type): Response
    {
        return $this->render('back/type/show.html.twig', [
            'type' => $type,
        ]);
    }

    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Type $type, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TypeType::class, $type);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $type->setUpdatedAt(new DateTimeImmutable());
            $entityManager->flush();

            return $this->redirectToRoute('app_back_type_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/type/edit.html.twig', [
            'type' => $type,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'delete', methods: ['POST'])]
    public function delete(Request $request, Type $type, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$type->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($type);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_back_type_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/back/category/_delete_form.html.twig
<form method="post" action="{{ path('app_back_category_delete', {'id': category.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}">
    <button class="btn btn-danger m-2">Delete</button>
</form>

templates/back/category/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success m-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/back/category/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Category{% endblock %}

{% block body %}
<div class="container">
    <h1>Edit Category</h1>

    {{ include('back/category/_form.html.twig', {'button_label': 'Update'}) }}

    <a class='btn btn-primary m-2' href="{{ path('app_back_category_browse') }}">back to categories list</a>

    {{ include('back/category/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/back/category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}List of categories{% endblock %}


{% block body %}
<div class='container'>
    <h1>List of categories</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Subtitle</th>
                <th>Picture</th>
                <th>Home order</th>
                <th>Created at</th>
                <th>Last update</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for category in categories %}
            <tr>
                <td>{{ category.id }}</td>
                <td>{{ category.name }}</td>
                <td>{{ category.subtitle }}</td>
                <td>{{ category.picture }}</td>
                <td>{{ category.homeOrder }}/5</td>
                <td>{{ category.createdAt ? category.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ category.updatedAt ? category.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a title="details" class='btn btn-secondary mb-2' href="{{ path('app_back_category_read', {'id': category.id}) }}"><i class="fa-solid fa-plus fa-xl"></i></a>
                    <a title="edit" class='btn btn-info mb-2' href="{{ path('app_back_category_edit', {'id': category.id}) }}"><i class="fa-solid fa-pen-to-square fa-xl"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class= "d-flex justify-content-center">
        {{ knp_pagination_render(categories) }}
    </div>

    <a title="add" class='btn btn-primary m-2' href="{{ path('app_back_category_add') }}">New category</a>
</div>
{% endblock %}

templates/back/category/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Category{% endblock %}

{% block body %}
<div class='container'>
    <h1>Create new Category</h1>

    {{ include('back/category/_form.html.twig') }}

    <a class='btn btn-primary m-2' href="{{ path('app_back_category_browse') }}">back to categories list</a>
</div>
{% endblock %}

templates/back/category/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categories{% endblock %}

{% block body %}
<div class="container">
    <h1>{{ category.name }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ category.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ category.name }}</td>
            </tr>
            <tr>
                <th>Subtitle</th>
                <td>{{ category.subtitle }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ category.picture }}</td>
            </tr>
            <tr>
                <th>Home order</th>
                <td>{{ category.homeOrder }}/5</td>
            </tr>
            <tr>
                <th>Created at</th>
                <td>{{ category.createdAt ? category.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Last update</th>
                <td>{{ category.updatedAt ? category.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a class='btn btn-primary m-2' href="{{ path('app_back_category_browse') }}">back to categories list</a>

    <a title="edit" class='btn btn-info' href="{{ path('app_back_category_edit', {'id': category.id}) }}"><i class="fa-solid fa-pen-to-square fa-xl"></i></a>

    {{ include('back/category/_delete_form.html.twig') }}
</div>
{% endblock %}